### ISSUE TITLE
Images!

### ISSUE THREAD

**Issue by FWirtz** [openclimatefix/openclimatefix.github.io#19]
Apart from the logos there is currently not a single picture on the website.
We should at least add an image to every single blogpost, even if it's stock footage.
To integrate with Medium we'd need to have one anyways.

We should also look in what other places we can put images as well. 😊 

**ToDos**
- [ ] Research good CC0 images to use
- [ ] Update `gatsby-node.js` to support images
- [ ] Add cover images to all blogs posts in `/src/posts/*`
