### ISSUE TITLE
[META] Website Relaunch To-Dos

### ISSUE THREAD

**Issue by FWirtz** [openclimatefix/openclimatefix.github.io#4]
See [`@next` branch](https://github.com/openclimatefix/openclimatefix.github.io/tree/%40next).

- [ ] Add photo for the Team section
- [ ] Finalise design
- [ ] Not optimised for mobile or small screens (put this off until we've finalised design)
- [ ] Add donation link
- [ ] Add logo for OCF
- [ ] Investigate adding blog capabilities (e.g. via [GatsbyJS](https://www.gatsbyjs.org))
- [ ] Think about switching to some common css baseline (e.g. Bootstrap, Tailwind, ... 🤔)
- [ ] ...

**Comment by FWirtz** [comment]
@schillerk I added your thoughts from the email here. Did I miss anything?
I think most things are up to me to coordinate rn, will take care of them and get back then.

**Comment by schillerk** [comment]
Looks great, thanks!

On the last point, I've used a bunch of css frameworks and full on React libraries. During the day I help build [Lunar](https://github.com/airbnb/lunar), which is all CSS-in-JS through [withStyles](https://github.com/airbnb/react-with-styles)

I think it really depends on how much we'll be adding to the site in the future. If we'd like to host analysis and visualization or even full tools on the repo we could definitely benefit from a framework. In the meantime, I can clean up the CSS a bit. I've used SCSS a bunch in the past.

**Comment by JackKelly** [comment]
Thanks again @FWirtz and @schillerk for all your work on the website :)

**Comment by FWirtz** [comment]
@schillerk oh cool!

Agree. Probably for now it's not too needed. I just thought that something like bootstrap might be nice to quickly have a mobile friendly version as well. Let's defer this until I get the design sorted out with the designer. Will get some first input from him this week 😊 

I'll also add some blogging capabilities via gatsby this week, i.e. migrate your work onto there. Will keep you posted.

PS Good luck with the apartment search!!!

**Comment by FWirtz** [comment]
Closing in favor of https://github.com/openclimatefix/website.
